#!/usr/bin/python
#
# Copyright (C) 2012 Allis Tauri <allista@gmail.com>
# 
# degen_primer is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# indicator_gddccontrol is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
Created on Jun 19, 2012

Tool to compute degenerate primer parameters using BioPython

@author: Allis Tauri <allista@gmail.com>
'''

#imports
import sys
from DegenPrimer.StringTools import hr, wrap_text, print_exception
from DegenPrimer.DegenPrimerConfig import DegenPrimerConfig
from DegenPrimer.DegenPrimerConfigCLI import DegenPrimerConfigCLI
from DegenPrimer.DegenPrimerPipeline import degen_primer_pipeline
###############################################################################    

if __name__ == '__main__':
    args = DegenPrimerConfigCLI()
    try:
        #parse command line arguments and/or configuration file
        args.parse_configuration()
    except ValueError, e:
        #if not in batch mode, consider incorrect values as errors
        if not args.batch():
            print_exception(e)
            sys.exit(1)
        #in batch mode all values except do_blast flag are ignored anyway
        else: pass
    
    print ''
    if not args.batch():
        #single analysis mode
        sys.exit(degen_primer_pipeline(args))
    else:
        #batch analysis mode
        print wrap_text('Batch mode enabled. All command-line arguments '
                        'except "--do-blast" are discarded.\n')
        return_code = 0
        for config_file in args.config_files:
            config = DegenPrimerConfig()
            try:
                config.parse_configuration(config_file)
            except ValueError, e:
                print '\nUnable to perform analysis with the set of values given in "%s"' % config_file
                print_exception(e)
                continue
            config.do_blast = args.do_blast
            print hr(' Repeating analysis for %s ' % config_file)
            return_code |= degen_primer_pipeline(config)
            print hr('')
        sys.exit(return_code)